### ISSUE TITLE
Too many frames

### ISSUE THREAD

**Issue by sulei1998** [hongsukchoi/TCMR_RELEASE#15]
Thanks for your work! When I tested my video with demo, I found that the number of frames became a lot. This will take me a long time to run the demo. I think it was caused by the followed command.
![image](https://user-images.githubusercontent.com/56378342/140248854-1fbc03a2-e395-49ad-8f17-394675a06e51.png)

So I changed the code and found that the number of frames decreased and the running speed was much faster. I wonder if this will affect the accuracy of the demo? My change is here：
![image](https://user-images.githubusercontent.com/56378342/140249284-df67c6fd-f048-43f6-a373-179dc18f3f4d.png)

**Comment by hongsukchoi** [comment]
Hi @sulei1998,

it depends on the fps of the input video. The pretrained model is trained on 25~30fps videos.
So I set the demo code to read video by 30 frames per second.
If your video originally has low fps, the number of frames will increase and the image qualities will decrease than what you know.

**Comment by sulei1998** [comment]
Thank you for your reply. Actually, my video is generated from a sequence of pictures, but this happens when I set the FPS of the generated video to 1 or 30. When I cancelled that line, everything was better and the effect looked good.
