### ISSUE TITLE
About preprocessing from videos to images in h36m datasets

### ISSUE THREAD

**Issue by MooreManor** [hongsukchoi/TCMR_RELEASE#17]
Hello. Thanks for your great work!
Can you offer the preprocessing file of changing videos in h36m to images whose format is like `s_01_act_02_subact_01_ca_01*.jpg` and generating corresponding json files like `Human36M_subject*_data.json`?
Thanks!

**Comment by hongsukchoi** [comment]
Hi, thanks for your interest!
Moon did the parsing work. 
Will you ask him? (make an issue here: https://github.com/mks0601/I2L-MeshNet_RELEASE)
