### ISSUE TITLE
Tranning Needed memory size

### ISSUE THREAD

**Issue by amituofo1996** [hongsukchoi/TCMR_RELEASE#29]
Hi,
My computer have 23GB memory, when I start trainning repr_table6_h36m_model.yaml, I can only load needed 2d data and 3d data.
How can I do? Can I separate 3D data and train stage by stage? are you still remeber your experiment memory?

**Comment by amituofo1996** [comment]
Can you tell me about your trainning time?

**Comment by hongsukchoi** [comment]
Hi, it took approx 55GB.

My recommendation is to discard 1/3 - 1/2 of the whole dataset in a random manner and train with the remaining data. It would give similar accuracy

**Comment by amituofo1996** [comment]
Thanks for your quick reply!
