### ISSUE TITLE
Difference number of frames between TCMR and SPIN

### ISSUE THREAD

**Issue by linjing7** [hongsukchoi/TCMR_RELEASE#32]
Hi, thanks for your excellent work. I found that in SPIN, the total number of frames in 3DPW dataset is 35515. But in TCMR, the 3DPW frames number is 34561. Could you please tell me what causes the difference?

**Comment by hongsukchoi** [comment]
Hi,

I followed VIBE.
I don't remeber exactly, but it has to do with this line:    
[ indices_to_use = np.where((dataset['joints2D'][:, :, 2] > VIS_THRESH).sum(-1) > MIN_KP)[0]](https://github.com/hongsukchoi/TCMR_RELEASE/blob/ade5ab5e2bd8b1a26338406c0b272d2a16f85070/lib/data_utils/threedpw_utils.py#L167)

**Comment by linjing7** [comment]
Okay, thank you very much!
